---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: ecommerce
data:
  WORDPRESS_DB_HOST: wordpress-mysql
  WORDPRESS_DB_NAME: wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: ecommerce
type: Opaque
data:
  WORDPRESS_DB_USER: d29yZHByZXNz # Base64 encoded 'wordpress'
  WORDPRESS_DB_PASSWORD: c2VjcmV0cGFzcw== # Base64 encoded 'secretpass'
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M= # Base64 encoded 'rootpass'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: wordpress-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: wordpress-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
