apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      version: v1           # Pod label to be used by Service to select the pods from this deployment
  replicas: 1            # number of replica of the Pods
  template:
    metadata:
      labels:
        env: dev         # Pod's label
        app: database
        version: v1
    spec:
      containers:
      - name: database-container
        image: mariadb:10.6.4-focal   # which image it will use
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3306    # Port exposed by container inside the Pod
        envFrom:
          - configMapRef:
              name: db-configmap
              optional: false
          - secretRef:
              name: db-secret
              optional: false