apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    version: v1       # label of the service
spec:
  type: ClusterIP
  ports:
  - port: 3306            # the port on which the service is listening
    protocol: TCP
    targetPort: 3306     # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    env: dev         # Pod's label
    app: database
    version: v1