apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  labels:
    app: wordpress
    env: dev
data:
  WORDPRESS_DB_HOST: "db-service.wordpress.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"